-- GrantEase seed corpus. Run once against the connected project.
-- Deadlines are relative to the run date so the demo never goes stale.
-- Six recurring prompt_theme values make essay clustering visible.

insert into public.scholarships
  (name, provider, amount_cents, deadline, essay_required, essay_word_count,
   recommendations_required, eligibility_summary, prompt_text, prompt_theme,
   applicant_pool_estimate, effort_score, win_probability, external_url, tags)
values
('Rising Scholars Community Award','Rising Scholars Foundation',150000,(current_date + 18),true,500,1,'Undergraduates with a documented record of local volunteering.','Describe a problem in your community and the concrete role you played in addressing it.','Community impact',620,28,0.180,'https://example.org/rising-scholars',array['community','undergraduate']),
('Neighborhood Builders Grant','Civic Trust of the Midwest',250000,(current_date + 34),true,650,1,'Students from the Midwest enrolled full time.','Tell us about a time you organized people around a shared goal.','Community impact',1400,42,0.090,'https://example.org/neighborhood-builders',array['community','leadership','midwest']),
('Main Street Service Scholarship','Main Street Merchants Alliance',75000,(current_date + 11),true,400,0,'Any enrolled student who has completed 40+ service hours.','How has serving your community changed the way you see your future?','Community impact',310,22,0.240,'https://example.org/main-street',array['community','quick']),
('First Light Scholarship','First Light Education Fund',500000,(current_date + 52),true,750,2,'First-generation college students with demonstrated need.','What does being the first in your family to attend college mean to you?','First-generation journey',3200,68,0.045,'https://example.org/first-light',array['first-generation','need-based','competitive']),
('Pathfinder First-Gen Award','Pathfinder Alumni Network',200000,(current_date + 27),true,500,1,'First-generation students in their sophomore year or later.','Describe the person or moment that convinced you college was possible.','First-generation journey',890,35,0.130,'https://example.org/pathfinder',array['first-generation']),
('Family Legacy Starter Grant','Legacy Starters Coalition',100000,(current_date + 9),true,350,0,'First-generation students, any major.','What legacy do you want to start for the people who come after you?','First-generation journey',450,20,0.210,'https://example.org/family-legacy',array['first-generation','quick']),
('Resilience Scholarship','Open Door Charitable Trust',350000,(current_date + 45),true,700,1,'Students who have overcome significant personal hardship.','Write about an obstacle that reshaped your approach to school.','Overcoming adversity',2600,60,0.055,'https://example.org/resilience',array['adversity','need-based']),
('Second Chance Education Award','Second Chance Learning Fund',120000,(current_date + 21),true,500,0,'Returning or non-traditional students aged 20+.','What brought you back to school, and what keeps you here?','Overcoming adversity',540,30,0.160,'https://example.org/second-chance',array['adversity','non-traditional']),
('Steady Hands Caregiver Grant','Steady Hands Foundation',90000,(current_date + 14),true,400,0,'Students balancing coursework with caregiving responsibilities.','Describe how you balance caregiving with your studies.','Overcoming adversity',280,24,0.230,'https://example.org/steady-hands',array['adversity','caregiver','quick']),
('Horizon Career Vision Scholarship','Horizon Futures Institute',400000,(current_date + 62),true,800,2,'Juniors and seniors with a defined post-graduation plan.','Where do you see your field in ten years, and what is your role in it?','Career vision',4100,72,0.035,'https://example.org/horizon',array['career','competitive']),
('Trade & Technology Futures Award','Applied Skills Council',180000,(current_date + 30),true,500,1,'Students in applied technology, trades, or engineering programs.','What problem do you want your career to solve?','Career vision',760,38,0.120,'https://example.org/trade-futures',array['career','engineering','technology']),
('Career Launch Micro-Grant','Launchpad Careers',50000,(current_date + 7),true,300,0,'Any student with an internship or job offer to fund travel/equipment.','In 300 words, what will this grant let you say yes to?','Career vision',190,15,0.280,'https://example.org/career-launch',array['career','quick','micro']),
('Nova STEM Innovation Prize','Nova Research Collective',750000,(current_date + 88),true,1000,2,'STEM majors with a research or prototype project.','Describe an original idea you have prototyped or researched.','STEM innovation',5200,85,0.020,'https://example.org/nova-stem',array['stem','research','competitive']),
('Women in Engineering Scholarship','Society of Applied Engineers',300000,(current_date + 40),true,600,1,'Women enrolled in an accredited engineering program.','What drew you to engineering and what will you build with it?','STEM innovation',1800,52,0.070,'https://example.org/women-in-engineering',array['stem','engineering','women']),
('Data for Good Fellowship','Data for Good Alliance',250000,(current_date + 56),true,650,1,'Students in data science, statistics, or computer science.','Describe a dataset you would use to improve a public service.','STEM innovation',1100,48,0.085,'https://example.org/data-for-good',array['stem','data','computer science']),
('Bio Futures Lab Grant','Bio Futures Lab',220000,(current_date + 35),true,550,1,'Life sciences majors with lab experience.','What biological question keeps you up at night?','STEM innovation',940,44,0.095,'https://example.org/bio-futures',array['stem','biology']),
('Campus Leadership Award','National Campus Leaders Council',175000,(current_date + 24),true,500,1,'Students holding a leadership role in a recognized campus organization.','How have you made an organization you lead better than you found it?','Leadership in service',1250,40,0.110,'https://example.org/campus-leadership',array['leadership','community']),
('Servant Leader Scholarship','Bridgewater Service Guild',130000,(current_date + 16),true,450,1,'Students with a sustained service commitment of 12+ months.','Describe leadership without a title.','Leadership in service',480,26,0.190,'https://example.org/servant-leader',array['leadership','community','quick']),
('Peer Mentor Recognition Grant','Student Success Network',60000,(current_date + 12),true,300,0,'Students serving as peer mentors, tutors, or RAs.','What has mentoring taught you about learning?','Leadership in service',240,18,0.260,'https://example.org/peer-mentor',array['leadership','quick','micro']),
('Regional Merit Scholarship','State Higher Education Board',500000,(current_date + 70),false,null,0,'Residents with a 3.5+ GPA attending an in-state institution.',null,null,6800,12,0.060,'https://example.org/regional-merit',array['merit','no-essay','competitive']),
('Dean''s Commitment Award','Association of Independent Colleges',220000,(current_date + 48),false,null,1,'Students in good academic standing nominated by a faculty member.',null,null,900,25,0.140,'https://example.org/deans-commitment',array['merit','no-essay']),
('Textbook Relief Fund','Campus Basic Needs Coalition',40000,(current_date + 6),false,null,0,'Any enrolled student who reports a textbook cost gap.',null,null,150,8,0.320,'https://example.org/textbook-relief',array['need-based','no-essay','quick','micro']),
('Commuter Transit Grant','Regional Transit Education Fund',35000,(current_date + 19),false,null,0,'Students commuting more than 15 miles to campus.',null,null,210,10,0.300,'https://example.org/commuter-transit',array['need-based','no-essay','quick','micro']),
('Rural Roots Scholarship','Rural Futures Trust',280000,(current_date + 58),true,600,1,'Students from towns with populations under 25,000.','How has where you grew up shaped what you want to study?','Community impact',700,46,0.100,'https://example.org/rural-roots',array['community','rural']),
('Veteran Family Education Grant','Veteran Family Support Fund',450000,(current_date + 75),true,700,1,'Veterans and dependents of service members.','What has service taught you that a classroom could not?','Overcoming adversity',1600,55,0.065,'https://example.org/veteran-family',array['veteran','adversity']),
('Arts & Culture Advancement Prize','Metro Arts Endowment',200000,(current_date + 41),true,550,1,'Students in visual, performing, or literary arts programs.','Describe the work you most want to make and who it is for.','Career vision',830,43,0.105,'https://example.org/arts-advancement',array['arts','career']),
('Green Campus Innovation Award','Sustainable Campus Fund',260000,(current_date + 66),true,600,1,'Students proposing a sustainability project on their campus.','What would you change about how your campus uses resources?','STEM innovation',1050,50,0.080,'https://example.org/green-campus',array['stem','sustainability']),
('Future Educators Scholarship','Teach Forward Foundation',240000,(current_date + 37),true,550,2,'Education majors committing to teach for two years post-graduation.','Why teaching, and why now?','Career vision',980,47,0.090,'https://example.org/future-educators',array['career','education'])
on conflict do nothing;
